- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: https://github.com/AFHH999/Dotfiles
    dest: "{{ ansible_facts['user_dir'] }}/Dotfiles"
    version: main

- name: Stow dotfiles packages
  ansible.builtin.command:
    cmd: "stow -R -d {{ ansible_facts['user_dir'] }}/Dotfiles -t {{ ansible_facts['user_dir'] }} {{ item }}"
  loop:
    - nvim
    - zsh
    - tmux
    - hypr
  changed_when: false
  failed_when: false

- name: Set zsh as default shell for the current user
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh
  when:
    - ansible_facts['os_family'] == "Archlinux"
    - ansible_facts['user_shell'] != "/usr/bin/zsh"
