$ANSIBLE_VAULT;1.1;AES256
64666661636639653537313364383632373535376137346166363831383364333338346538663432
3165353437643263356430613163393938626230333637320a623466623530613331643335363565
63666130626165633839353134613363353631613735346535663732313234623163303637306133
3737636663333461370a383236616430393338633530663033386661333464303533383734373738
33663635343863643864653763373362323062656464383165393333343532313761316261373764
63653966363137626361356461653134633763363539643337336235623036386334343362306265
623837336366363933353066333933373163
